### ISSUE TITLE
--find option not working with directories?

### ISSUE THREAD

**Issue by dlethin** [jdberry/tag#25]
I seem to have no problem tagging files and directories, but when performing a query using find, only my tagged files show up.  Is this expected, or is there another option to include directories?

```
$ find . -name ".vagrant" |xargs tag -s blah
$ tag -l .vagrant
.vagrant                       	blah
$ find . -name "dummyfile" |xargs tag -s blah
$ tag --find blah .
<PATH_TO_MY_FILE>/dummyfile
```

Use the output of find as input to another script for further processing, but it needs to process tagged directories as well.

Thanks.

**Comment by jdberry** [comment]
@dlethin I don't believe the issue is that --find doesn't find directories. It does. This is issue is that it doesn't find "invisible" directories that start with dot.

I'm pretty sure this is a function of the underlying metadata store. Spotlight either doesn't index, or doesn't search in, directories that have a name starting with a dot. I don't see any ways at the moment to circumvent this, though I'd be happy for a tip if you have one.

You can tag with the match option, and -A (to find invisible files) if you know the directory root in which to look for your files.

Here, d1 and .d3 are directories, and foo is a file... Note that the tagged directory is found by find as long as it doesn't start with a dot.

    % tag -Aetm blah .
    .d3                            	blah
    d1                             	blah
    foo                            	blah

    % tag -f blah .
    path.../d1
    path.../foo

**Comment by dlethin** [comment]
Thanks -- this provides me with a solution I can press forward with.  Cheers.

**Comment by jdberry** [comment]
@dlethin: Note that the major difference between --find and --match is that match does a (potentially recursive) scan of a directory, while find asks the system to look in its metadata database. Depending on how big a directory you ask it to scan, match could be significantly more expensive to perform, so you'd be advised to try to limit the size of the subtrees you're attempting to match within. Alternatively, you could consider other options such as tagging some other file or directory that doesn't start with a dot, but that happens to be coincident with your .vagrant directories (and thus which --find would find). Anyway, thanks for the report, and good luck.
