### ISSUE TITLE
adding tag with certain characters damages file

### ISSUE THREAD

**Issue by workflowsguy** [jdberry/tag#32]
On several times now, I have encountered a situation where after adding a tag to a PDF file in a shell script with

`tag -a "$tags" "$file"`

the file was damaged as a result. With a hex editor, I could see that the beginning of the file was overwritten by the xattr information (`bplist00`etc.)

It is the same when I enter the command above in the Terminal, replacing the variables with their actual values.

This is seemingly caused by certain characters in the tag, but I have not found out which ones. 

Using Tag 0.9 installed through Homebrew on OS X 10.11.6

**Comment by jdberry** [comment]
Hi @workflowsguy. I'm not aware of an issue here, and any issue that actually does exist is likely within the OS or frameworks, since tag just calls into MacOS frameworks code to do the work of altering tags.

If you can come up with a specific example that breaks it would be great. As-is, I don't have much to go on.
